### ISSUE TITLE
Add achievements to walkthrough

### ISSUE THREAD

**Issue by edderiofer** [andrewschultz/you-wont-get-her-back#16]
As per the title; the walkthrough doesn't show how to get all the achievements (and I'm already out of ideas).

**Comment by andrewschultz** [comment]
Acknowledged! I found it hard to balance giving people hints about what to do with not spoiling too much at once.

I think I have some good ideas for a "see it all" walkthrough that can only spoil one achievement at a time. While it may take more than a day, it's a good goal, and it's one I wish I'd started on before the comp release.

Thanks again for reporting these bugs. They're a big help.

**Comment by andrewschultz** [comment]
I added the walkthroughs to source control. They should be on itch.io next time I compile the binaries, etc.
