### ISSUE TITLE
"Running Up The Score" achievement appears to be impossible to obtain

### ISSUE THREAD

**Issue by edderiofer** [andrewschultz/you-wont-get-her-back#21]
I'm not very well-versed with Inform 7, but looking through the story file, it seems like `sucker-sacrificing` is removed from `available-fleestate-list` on game start and is never added back after you first win, so the black rook will never move to a8 to let you get this achievement?

**Comment by andrewschultz** [comment]
You're right. Great catch. I made a mistake there both in coding and programmer-testing.

My test scripts forced the rook to a certain square, so I never caught this. I had added useless-sacrificing after the first checkmate. I need to add a line as below.

```
			if ever-won is false:
				now ever-won is true;
				say "You figured the main solution, but if you want, you can [b]TRY[r] to find other ways to lose. I hope they are amusing. There are a few more squares the enemy rook may flee to now, making for more endings.";
				add useless-sacrificing to available-fleestate-list; [forgot to add a line here]
				add spite-checking to available-fleestate-list;
```

This was again a late addition to the code--I didn't want the player to see certain scenarios first--but given it happened, I would like to run another test script to test all the ways through without my commands to force the rook to a certain square. This is tricky, as I need to bypass how the game shuffles the rook-flee types. But it's not esoteric
